@echo off
cd %~dp0
pushd .\helpPage
echo Compiling HTML...
cmd /c pnpm build
echo Done...
popd
echo Compiling AHK script...
start /b /wait "" ".\ahk\build.ahk"
echo Done...
echo Updating README...
start /b /wait "" ".\md\build.ahk"
echo Done
